### PR TITLE
fix: rename reserved word - extends

### LINKED ISSUE #43: Remove use of extends reserved word
https://github.com/pubfood/pubfood/blob/master/src/util.js#L35 uses `extends` as a function name which is a reserved word.

Later versions of JS engines appear tolerant of this; however, WebKit 533.1 at android 2.3.7 appears not to be tolerant of this and fails to parse "_pubfood.js_".
__v0.1.14__

```
build/pubfood.js: 703
SyntaxError: ParseError
```

 Genymotion - Motorola Droid Razr - 2.3.7
`about:debug` to show javascript console in android browser

### PR DESCRIPTION
**Pull request by elljoh**
Closes #43 

+ Tests
+ Added missing parent object constructor arguments

### CODE REVIEW

File: src/util.js [hunk 1]
```diff
@@ -43,10 +43,18 @@ var util = {
       return parent;
     });
 
-    child.prototype.init_ = function() {
-      var parents = this.parents || [];
+    child.prototype.init_ = function(a1, a2, a3, a4, a5) {
```
Comment (elljoh) [inline src/util.js]: @fatihcode would you mind reviewing this addition in particular.

This `init_` function is internal only and is not intended for public API use. However, when making the update to fix the `extends` reserved word usage, I wanted to have children pass arguments to parent constructors.

Rudimentary change, but using `call` with argument lists may not be best case.

Interested in your opinion on this.

Also, happy to revert this update in particular to keep the commit more concise.
