### PR TITLE
fix(event): flush immediate observers

### LINKED ISSUE #10: Flush PubfoodEvent immediate observers on removeAllListeners
The `PubfoodEvent.removeAllListeners` method should flush the `PubfoodEvent.observeImmediate_` listener object.

In unit tests, it is observed that tests expecting certain events to exist in a particular order, left over event objects in the `observeImmediate_` property cause assertions to fail unexpectedly.

### Reproduce
Create some events
```
Event.on(Event.EVENT_TYPE.BID_PUSH_NEXT, function() { console.log('push next bid'); });
PubfoodEvent {auction_: 1, observeImmediate_: Object, _events: Object}
Event.publish('BID_PUSH_NEXT', {}, 'p1');
VM15086:1 push next bid
true
Event.publish(Event.EVENT_TYPE.BID_COMPLETE, {}, 'p1');
true
Event.on(Event.EVENT_TYPE.BID_COMPLETE, function() { console.log('completed bidding'); });
VM15183:1 completed bidding
PubfoodEvent {auction_: 1, observeImmediate_: Object, _events: Object}
```
Notice `_events` and `observeImmediate_` object contents
```
Event._events
Object {BID_PUSH_NEXT: EE}
Event.observeImmediate_
Object {BID_COMPLETE: Array[1]}
```
See `observeImmediate_` after `removeAllListeners`
```
Event.removeAllListeners()
PubfoodEvent {auction_: 1, observeImmediate_: Object, _events: Object}
Event._events
Object {}
Event.observeImmediate_
Object {BID_COMPLETE: Array[1]}
```

### Proposal
```
PubfoodEvent.prototype.removeAllListeners = function(event) {
  EventEmitter.prototype.removeAllListeners.apply(this, arguments);

  this.observeImmediate_ = {};

  return this;
}
```

### PR DESCRIPTION
**Pull request by elljoh**
closes #10 

Mainly an issue for asynchronous tests. The _so called_ "immediate observers" aka `PubfoodEvent.observeImmediate_` event listeners are not removed from the `PubfoodEvent` singleton.

In a single page view this would not be an issue, but it is possible that on a pubfood `refresh` this could produce undesired event listener invocation and difficult to debug issues.

### CODE REVIEW

**Comment by elljoh** [comment]
Tests need more coverage.

**Comment by elljoh** [comment]
Closing in lieu of test coverage update.

**Comment by elljoh** [comment]
Fix needed for current implementation to address listener removal. We will revise the event handling use cases in a major release (_and possibly in a minor_ for refinement).

File: src/event.js [hunk 1]
```diff
@@ -181,60 +188,25 @@ PubfoodEvent.prototype.publish = function(eventType, data, eventContext) {
   });
 };
 
-/**
- * Emit an event to all registered event listeners.
```
Comment (elljoh) [inline src/event.js]: no real point having `@private` jsdoc referencing external git repo.

added specific jsdoc to extended EventEmitter functions.

File: src/event.js [hunk 2]
```diff
@@ -254,4 +240,25 @@ PubfoodEvent.prototype.on = function(event, fn) {
...
+ *
+ * @param {string} event the event type
+ * @return {PubfoodEvent} - this
+ * @extends EventEmitter
+ * @private
+ */
+PubfoodEvent.prototype.removeAllListeners = function(event) {
+  EventEmitter.prototype.removeAllListeners.call(this, event);
+
+  this.observeImmediate_ = {};
```
Comment (elljoh) [inline src/event.js]: after calling the super type to remove the `event`, reset the immediate observers map.

File: test/api-callbacks.js [hunk 3]
```diff
@@ -39,18 +39,12 @@ var auctionExample = require('./fixture/auctionexample1');
 
 describe('Api Callbacks - Tests', function() {
 
-  function clearEvents() {
```
Comment (elljoh) [inline test/api-callbacks.js]: Simply use the new `PubfoodEvent.removeAllListeners()` method.

This cleanup is repeated for a couple of test files.

File: test/event/index.js [hunk 4]
```diff
@@ -10,8 +10,44 @@ var Event = require('../../src/event');
 describe('Event - Tests', function () {
   beforeEach(function() {
     Event.removeAllListeners();
-    // TODO consider if this should be a formal API instead
-    Event.observeImmediate_ = {};
+  });
+  it('should remove all listeners', function(done) {
```
Comment (elljoh) [inline test/event/index.js]: Test both:
 - standard `on` <= `emit` call sequence
 - unconventional `emit` => `on` sequence
  - i.e. typically we'd see that if there are no listeners an event is not emitted. However, we can see cases, such as slow net connections or with throttling net, an event may be emitted before the listener is added with `on`.
    <p>A case in point is the `POST_AUCTION_RUN` event listener positioned close to the closing `</body>` element and the pubfood auction runs in the header; it has been seen and tested that with throttling enabled, the event is emitted before the listener is added.

File: test/mediator/auctionmediator.js [hunk 5]
```diff
@@ -67,7 +61,7 @@ describe('Pubfood AuctionMediator', function testPubfoodMediator() {
   });
 
   afterEach(function() {
```
Comment (solenoid) [inline test/mediator/auctionmediator.js]: This `afterEach` is not needed since the concerns are already dealt with in the `beforeEach` so I'd say this should just be removed here and in the other place `afterEach` is being used.

File: test/api-callbacks.js [hunk 6]
```diff
@@ -39,18 +39,12 @@ var auctionExample = require('./fixture/auctionexample1');
...
-    Event.observeImmediate_ = null;
-    Event.observeImmediate_ = {};
-  }
-
   beforeEach(function() {
-    clearEvents();
+    Event.removeAllListeners();
   });
 
   afterEach(function() {
```
Comment (solenoid) [inline test/api-callbacks.js]: I'd say remove this whole function since it isn't needed.

Comment (elljoh) [inline test/api-callbacks.js]: Did you mean that neither `beforeEach` or `afterEach` ?

w/o `beforeEach`, `Event.removeAllListeners()` some tests are not run and this looks like an issue with the test code.

Looking at this.

Comment (elljoh) [inline test/api-callbacks.js]: Wrt the above, if `Event.removeAllListeners()` is not called `beforeEach`, the _api-callbacks.js_ test `AUCTION_COMPLETE` listener is invoked prematurely; there are no `bidProviderDoneCalled` keys defined an the test `done()` is called w/o errors.

Will uncomment [these lines in api-callbacks.js](https://github.com/pubfood/pubfood/blob/master/test/api-callbacks.js#L60-L62) to cover this for false positives.

**Comment by solenoid** [comment]
:+1: lgtm
